ДЗ 3
droidroot1995/2019-2-Track-Frontend-A-Goryakin pull request #14
Opened 2020-03-15 16:30 UTC by droidroot1995

# Домашнее задание № 3
Прошу @martinkomitsky или @chexex проверить его.
Что было сделано: 
* Установлен css-sprite-loader
* Сделана виртуальная клавиатура Emoji
* Emoji отображаются вместе с текстом

2020-03-18 09:20 UTC, martinkomitsky requested changes

2020-03-18 09:20 UTC, martinkomitsky commented on package.json
> +    "react-app-rewired": "^2.1.5",
где в ДЗ было сказано использовать данный пакет? несколько раз за время учебы говорилось, что использовать такого вида пакеты - очень глупо и бессмысленно. Придется вспомнить про eject, который мы обсуждали 100 раз

2020-03-18 09:20 UTC, martinkomitsky commented on src/components/Emoji.js
> +/* eslint-disable jsx-a11y/no-static-element-interactions */
зачем отключать правила? самовыстрел в ногу

2020-03-18 09:20 UTC, martinkomitsky commented on package.json
> +    "react-substring": "^0.1.6",
вообще, про дополнительные пакеты тоже не говорилось использовать, но если совсем лень, то можно оставить......

2020-03-18 09:20 UTC, martinkomitsky commented on src/components/Emoji.js
> +export const Smile = connect(null, mapDispatchToProps)(SmileEmoji)
* зачем экспортировать все эмоджики? А что, если у тебя их будет 10000?
* зачем и каким боком тут встал редакс в этот компонент?

Все, что надо было сделать - разработать тупой компонент, который принимает `props` с указанным типом (кодом) эмоджи и рисует его. 

В компоненте `messageBubble` (или как он на самом деле называется у тебя) надо сделать парсинг на наличие этих самых кодов эмоджи и прокидывать в этот компонент из текста выше

2020-03-18 09:20 UTC, martinkomitsky commented on src/components/EmojiKeyboard.js
> +    </div>
кошмар. 

`<Crying name=":crying:" />`

В чем смысл уникальных компонентов, если они еще принимают в себя параметр, который еще раз дублирует код эмоджи?
Лучше сделать один компонент, куда прокидывать этот код

2020-03-18 09:20 UTC, martinkomitsky commented on src/components/MessageBubble.js
> +/* eslint-disable no-unused-vars */
надо переставать выключать правила линтера

2020-03-18 09:20 UTC, martinkomitsky commented on src/components/MessageBubble.js
> +  let tmp = (
это все должно сократиться при новой логике

2020-03-18 09:21 UTC, martinkomitsky requested changes
нужно переделать работу с эмоджиками и лоадером

2020-03-18 11:05 UTC, droidroot1995 commented on src/components/EmojiKeyboard.js
> +    </div>
Также забыл убрать, думал их использовать при клике, но данный вариант не сработал.

2020-03-18 11:07 UTC, martinkomitsky commented on src/components/EmojiKeyboard.js
> +    </div>
интересно. В любом случае тут напрашивается один компонент

2020-03-18 11:08 UTC, droidroot1995 commented on package.json
> +    "react-app-rewired": "^2.1.5",
Если сделать eject, то перестаёт работать storybook, т.к. требует установить react-scripts. При установке react-scripts используется по дефолту конфиг, прописанный в данном пакете. Установка react-app-rewired единственный способ, который нашёл, чтобы работали и storybook и emoji.

2020-03-18 11:11 UTC, droidroot1995 commented on src/components/Emoji.js
> +export const Smile = connect(null, mapDispatchToProps)(SmileEmoji)
Редакс используется для вставки эмодзи в строку, т.к. у меня нет прямого доступа из EmojiKeyboard в FormInput.

2020-03-18 11:11 UTC, droidroot1995 commented on src/components/MessageBubble.js
> +/* eslint-disable no-unused-vars */
Было сделано временно, забыл убрать эту строку.

2020-03-18 11:17 UTC, martinkomitsky commented on package.json
> +    "react-app-rewired": "^2.1.5",
по идее, это 2 разных пакета которые работают друг от друга независимо. Сторибук можно настроить и без реакт скриптс. Если он перестает работать прямо сейчас, то можно на него забить, а починить позже

2020-03-18 11:49 UTC, droidroot1995 commented on src/components/EmojiKeyboard.js
> +    </div>
Думал сделать обработку клика на компонент в EmojiKeyboard, он не срабатывает, срабатывает только в самом Emoji.

2020-03-18 11:50 UTC, droidroot1995 commented on package.json
> +    "react-app-rewired": "^2.1.5",
Это, скорее всего, из-за того, что storybook использует шаблон для React.

2020-03-18 15:18 UTC, droidroot1995 commented
Всё поправил.

2020-03-22 17:07 UTC, martinkomitsky requested changes
Исправить замечания. Дополнительно в конфиге webpack не нашел секции для sprite css loader

2020-03-22 17:07 UTC, martinkomitsky commented on src/tests/__snapshots__/MessageBubble.test.js.snap
> +    className="undefined undefined"
а почему стало так?

2020-03-22 17:07 UTC, martinkomitsky commented on src/tests/__snapshots__/MessageBubble.test.js.snap
> +  className="undefined undefined"
и тут почему так?

2020-03-22 17:07 UTC, martinkomitsky commented on src/components/replacer.js
> +/* eslint-disable prefer-destructuring */
??

2020-03-22 17:07 UTC, martinkomitsky commented on src/components/replacer.js
> + ** Taken from https://github.com/iansinnott/react-string-replace/blob/master/index.js
отличное решение - просто выкинуть зависимость одной библиотеки, перенести ее код к себе и затащить кучу другого кода к себе (lodash). В чем был смысл всей этой канители?)

2020-03-22 17:07 UTC, martinkomitsky commented on src/components/EmojiKeyboard.js
> +  )
как можно заменить всю эту структуру так, чтобы она занимала не больше 4 строк?

2020-03-22 17:07 UTC, martinkomitsky commented on src/components/Emoji.js
> +  }
еще раз. Если у тебя будет 100000 емодзи? так и будешь добавлять кейсы?
...
все, что от тебя требовалось:
```
const emStyle = style[name];
```

Одна строчка на миллиард кейсов

2020-03-22 17:07 UTC, martinkomitsky commented on package.json
> +    "react-app-rewired": "^2.1.5",
пакет удаляешь?

2020-03-22 21:58 UTC, droidroot1995 commented
Всё исправил.

2020-03-22 22:05 UTC, droidroot1995 commented on src/components/EmojiKeyboard.js
> +  )
С помошью map

2020-03-25 17:23 UTC, chexex reviewed
Улучшить код возможностями es6. Лучше бы упростить функционал хелпера для замены подстроки в строке (уточнил в комментах)

2020-03-25 17:23 UTC, chexex commented on src/components/Emoji.js
> +const Emoji = (props) => {
```suggestion
const Emoji = ({setEmji, name, etype}) => {
```

2020-03-25 17:23 UTC, chexex commented on src/components/Emoji.js
> +  const { setEmji, name, etype } = props
```suggestion
```

2020-03-25 17:23 UTC, chexex commented on src/components/Emoji.js
> +  }
```js
const emName = !match ? `:${name}:` : name;
```

2020-03-25 17:23 UTC, chexex commented on src/components/Emoji.js
> +    emji = <span onClick={handleEmojiClick} className={emStyle} />
1 в 1 как на 25 строке? (`let emji = <span onClick={handleEmojiClick} className={emStyle} />`)

2020-03-25 17:23 UTC, chexex commented on src/components/EmojiKeyboard.js
> +/* eslint-disable no-plusplus */
```suggestion
```

2020-03-25 17:23 UTC, chexex commented on src/components/EmojiKeyboard.js
> +  let k = 0
```suggestion
```

2020-03-25 17:23 UTC, chexex commented on src/components/EmojiKeyboard.js
> +      {emojis.map((entry) => (
```suggestion
      {emojis.map((entry, idx) => (
```

2020-03-25 17:23 UTC, chexex commented on src/components/EmojiKeyboard.js
> +        <Emoji etype="kbd" key={k++} name={entry} />
```suggestion
        <Emoji etype="kbd" key={idx} name={entry} />
```

2020-03-25 17:23 UTC, chexex commented on src/components/FormInput.js
> +  const { placeholder, selected, emoji, sendMsg, clearEmji, filesDragAndDrop } = props
Вынести деструктуризацию в сигнатуру функции

2020-03-25 17:23 UTC, chexex commented on src/components/FormInput.js
> +    isEmojiKOpened: -1,
почему управление через -1? не `true`, `false`?
в -1 вижу смысл при семафорах, для простого да/нет понятнее (по крайней мере в мире js, python) использовать булевы примитивы :)

PS: после этого коммента не нужно менять все -1 и variable < 0, иначе уйдет много времени. Просто оставь мой коммент на будущее в голове :)

2020-03-25 17:23 UTC, chexex commented on src/components/FormInput.js
> +  }
`emojiKeyboard = (isEmojiKOpened < 0) && <EmojiKeyboard />`

2020-03-25 17:23 UTC, chexex commented on src/components/MessageForm.js
> +  const { selected, messages, userId, chatInfo } = props
Внести в параметры

2020-03-25 17:23 UTC, chexex commented on src/components/replacer.js
> +}
Не слишком ли сложный функционал для замены паттерна в строке? :))))

2020-03-25 18:05 UTC, droidroot1995 commented on src/components/replacer.js
> +}
А он не просто паттерн заменяет, делает замену на jsx. Насколько помню, если мы просто HTML'ку подставим, то react её экранирует :)

2020-03-25 18:09 UTC, droidroot1995 commented on src/components/EmojiKeyboard.js
> +        <Emoji etype="kbd" key={k++} name={entry} />
Вот в этом случае warning вылезает, что нельзя использовать индекс в массиве в качестве ключа :)

2020-03-25 18:44 UTC, droidroot1995 commented
@chexex пофиксил замечания :)

2020-03-26 17:12 UTC, martinkomitsky approved these changes
12

2020-03-26 17:12 UTC, merged