ДЗ 4
droidroot1995/2019-2-Track-Frontend-A-Goryakin pull request #15
Opened 2020-03-28 21:02 UTC by droidroot1995

# Домашнее задание № 4
Прошу @martinkomitsky, @chexex проверить его.
Что было сделано: 
* Добавлена поддержка websockets
*  Добавлена поддержка WebRTC (частично)

2020-03-31 20:00 UTC, chexex requested changes
Все хорошо, за исключением цикла с использованием `i++` :) Посмотреть на комментарии. В остальном понравилось.

2020-03-31 20:00 UTC, chexex commented on src/components/MessageFormRtc.js
> +    messages.forEach((msg) => {
```suggestion
    messages.forEach((msg, i) => {
```

2020-03-31 20:00 UTC, chexex commented on src/components/MessageFormRtc.js
> +  if (typeof messages !== 'undefined' && messages !== null && messages.length > 0) {
```suggestion
  if (messages && message.length > 0) {
```

2020-03-31 20:00 UTC, chexex commented on src/components/MessageFormRtc.js
> +        bubble = <MessageBubble className={styles.message_bubble.me} key={i} msgInfo={msg} />
Что если попробовать вот так:
```suggestion
      const bubble = <MessageBubble className={styles.message_bubble[msg.self ? 'me' : 'them']} key={i} msgInfo={msg} />
```

2020-03-31 20:00 UTC, chexex commented on src/components/MessageFormRtc.js
> +      i += 1
```suggestion
```

2020-03-31 20:00 UTC, chexex commented on src/components/MessageFormRtc.js
> +      msgList.push(bubble)
```js
msgLisg = messages.map(msg => {...})
```

2020-04-01 16:00 UTC, droidroot1995 commented
@chexex поправил код, учитывая все замечания :)

2020-04-03 07:02 UTC, chexex approved these changes
12 баллов

2020-04-03 07:02 UTC, merged