Finished second ht
droidroot1995/2019-2-Track-Frontend-A-Goryakin pull request #2
Opened 2019-10-06 11:44 UTC by droidroot1995

# Домашнее задание №2
Прошу @martinkomitsky, @chexex или @priver проверить его.
Что было сделано: 
* Реализован элемент MessageBubble
* Сверстана форма отправки сообщений по макету
* Добавлен ESlint
* Реализовано сохранение сообщений в localStorage
* Изменён .travis.yml
* Обновлён package.json для возможности привязки к TravisCI

2019-10-06 18:39 UTC, chexex submitted a review, later dismissed
Удалить из гита папки web-components/build, web-components/false
добавить web-components/.gitignore и добавить туда правила `build/`, `false/`
обновить travis.yml

2019-10-06 18:39 UTC, chexex commented on .travis.yml
>        - master
Добавить паттерн для сборки своих веток
```
branch:
  - master
  - devel
  - /^frontend_lesson_\d+$/
```

2019-10-06 19:33 UTC, droidroot1995 commented on .travis.yml
>        - master
Обновил .travis.yml, добавил web-components/.gitignore, удалил директории build, false.

2019-10-06 19:35 UTC, droidroot1995 commented
Обновил .travis.yml, добавил web-components/.gitignore, удалил директории build, false.

2019-10-11 13:52 UTC, droidroot1995 commented
@chexex Исправил, сверстанная версия страницы теперь отображается в gh-pages. Однако появился вопрос: почему отличается верстка в gh-pages и на локальном сервере?

2019-10-12 12:59 UTC, priver requested changes
![image](https://user-images.githubusercontent.com/1700074/66701806-33bca380-ed09-11e9-950c-0659bd33a286.png)
а почему картинка не круглая?

2019-10-12 13:57 UTC, droidroot1995 commented
> ![image](https://user-images.githubusercontent.com/1700074/66701806-33bca380-ed09-11e9-950c-0659bd33a286.png)
> а почему картинка не круглая?

@priver
![Chat screen](https://user-images.githubusercontent.com/4304506/66702516-2e635700-ed11-11e9-825f-c3c66c78e31b.png)
На локальном сервере всё отлично. Почему здесь не применяется нормально стиль для flex я, если честно, не могу понять.

2019-10-13 18:30 UTC, droidroot1995 commented
Всё поправил. Теперь верстка отображается нормально.

2019-10-14 11:06 UTC, priver approved these changes
Отлично, 12 баллов

2019-10-14 11:06 UTC, merged