Finished third ht
droidroot1995/2019-2-Track-Frontend-A-Goryakin pull request #3
Opened 2019-10-18 18:22 UTC by droidroot1995

# Домашнее задание №3
Прошу @martinkomitsky, @chexex или @priver проверить его.
Что было сделано: 
* Свёрстан макет списка чатов.
* Реализованы модули ChatList, ChatListItem, ChatListHeader, NewChatButton.
* Реализован переход между экраном списка чатов и экраном чата с передачей необходимых данных.
* Поправлена вёрстка ChatHeader

2019-10-20 11:33 UTC, martinkomitsky requested changes

2019-10-20 11:33 UTC, martinkomitsky commented on web-components/src/components/ChatList.js
> +        -webkit-flex-direction: row;
Все префиксные стили надо удалить. Во всех файлах. Это будем в будущем добавлять при помощи `autoprefixer`;

2019-10-20 11:33 UTC, martinkomitsky commented on web-components/src/components/ChatList.js
> +const template = document.createElement("template")
Желательно для js файлов выбрать 1 стиль кавычек (либо двойные, либо одинарные, но не смешанные). На это должно быть правило в линтере, если линтер не ругается на это, то это плохо

2019-10-20 11:33 UTC, martinkomitsky commented on web-components/src/components/ChatListItem.js
> +        	border-radius: 50px;
Во всех файлах нужно поправить отступы. все стили должны быть на одном уровне:
```
		.avatar {
			position: relative;
			display: inline-block;
        	        border-radius: 50px;
                  	border: 1px solid black;
        	        align-self: center;
        	        height: 90%;
		}
```

как сейчас:

```
		.avatar {
			position: relative;
			display: inline-block;
        	border-radius: 50px;
        	border: 1px solid black;
        	align-self: center;
        	height: 90%;
		}
```

2019-10-20 11:37 UTC, martinkomitsky commented
@droidroot1995 нужно исправить замечания + следующие:
* У тебя для каждого чата показывается один и тот же контент. Для каждого чата нужен отдельный (чтобы показывались разные сообщения)
* При написании сообщений не происходит скролл вниз
* Кнопка добавления чата не добавляет чат

2019-10-20 19:30 UTC, droidroot1995 commented
Все исправлено с учётом замечаний.

2019-10-21 17:01 UTC, martinkomitsky approved these changes
10 + 2

2019-10-21 17:02 UTC, merged