ДЗ 7
droidroot1995/2019-2-Track-Frontend-A-Goryakin pull request #7
Opened 2019-12-01 22:17 UTC by droidroot1995

# Домашнее задание № 7
Прошу @martinkomitsky, @chexex или @priver проверить его.
Что было сделано: 
* Загрузка изображений
* Загрузка файлов
* Определение местоположения
* Drag & Drop
* Запись аудио
* Отправка вложений на сервер

2019-12-05 13:37 UTC, priver requested changes

2019-12-05 13:37 UTC, priver commented on src/components/App.js
> +        msg += `<a href="${value.attachments[i].url}" style="margin-left: 30%;"><img src="${value.attachments[i].url}" width="70px" height="70px"></a><br>`
хранить в сторадже сообщения в виде HTML - плохая идея (об этом будет 10ая лекция)

2019-12-05 13:37 UTC, priver commented on src/components/MessageBubble.js
> +          <p className={styles.message} dangerouslySetInnerHTML={{ __html: msg }}></p>
dangerouslySetInnerHTML - лучше забыть что такое свойство вообще существует

2019-12-05 13:37 UTC, priver commented on src/components/MessageForm.js
> +      <div className={`${styles.drag_n_drop_wrapper} ${dragActiveState && styles.drag_n_drop_active}`}>
можно использовать пакет `classnames`

2019-12-05 14:52 UTC, droidroot1995 commented on src/components/App.js
> +        msg += `<a href="${value.attachments[i].url}" style="margin-left: 30%;"><img src="${value.attachments[i].url}" width="70px" height="70px"></a><br>`
Так, в localStorage хранится только текст сообщения, без разметки. А разметку добавил только для того, чтобы корректно отрисовать изображения, аудио и ссылки на геопозицию, без изменения MessageBubble.

2019-12-05 14:55 UTC, droidroot1995 commented on src/components/MessageBubble.js
> +          <p className={styles.message} dangerouslySetInnerHTML={{ __html: msg }}></p>
Возможно, да, здесь лучше передавать attachment и audio и отрисовывать их во время отрисовки сообщения. Это же также можно использовать при получении сообщений с сервера)

2019-12-09 13:07 UTC, priver requested changes

2019-12-09 13:07 UTC, priver commented on src/components/App.js
> +      msg: msg,
теперь мы кладем компоненты в стейт (
так не нужно делать, в стейте должны быть данные на основании которых рендерятся компоненты, а не сами компоненты

2019-12-16 16:17 UTC, priver approved these changes

2019-12-16 16:17 UTC, merged